# ./.tmuxinator.yml

name: blog
root: .

windows:
    - content:
        layout: main-horizontal
        panes:
            - cd content && lc
            - ./run-docker-compose-server-start.sh
            - sleep 5; source run-attach-to-running-container.sh
